version: '3.8'
services:
  gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./logs/nginx:/var/log/nginx"
    depends_on:
      - fastapi
      - playground
  fastapi:
    build: py-project
    
  playground:
    build: playground